"""
Build a lookup table for resource throughput features.

This script builds a lookup table mapping microarchitecture configurations to
throughput feature vectors. The lookup table is built once from the throughput
.npy files generated by the C++ simulator, then saved for reuse.

The lookup table maps:
  (resource, param_combo) -> 101-dim feature vector

Feature encoding (101 dimensions per distribution):
  - 50 percentiles of raw distribution (p1, p3, ..., p99)
  - 50 percentiles of size-weighted distribution
  - 1 mean value

Usage:
  # Build lookup table from throughput data
  python build_throughput_lookup.py -i ../output -o throughput_lookup.pkl

  # Test the lookup table
  python build_throughput_lookup.py -i ../output -o throughput_lookup.pkl --test
"""

import argparse
import pickle
import numpy as np
import pandas as pd
from pathlib import Path
from typing import Dict, Tuple, List, Optional

# Local imports
import utils
import models


class ThroughputLookupTable:
    """
    Lookup table for resource throughput features.

    Maps (resource, param_combo) -> 101-dim feature vector
    """

    def __init__(self, output_dir: str = "output"):
        """
        Initialize and build the lookup table.

        Args:
            output_dir: Directory containing the throughput .npy files
        """
        self.output_dir = Path(output_dir).resolve()
        self.data = {}  # raw data: {resource_name: (params, thr)}
        self.lookup = {}  # {resource_name: {param_tuple: feature_vector}}
        self.resource_order = []  # ordered list of resources
        self._column_names = None  # cached column names for DataFrame

        self._load_data()
        self._build_lookup()

    def _load_data(self):
        """Load all throughput data from output directory."""
        print(f"Loading throughput data from: {self.output_dir}")
        self.data = utils.load_all_throughputs(output_dir=str(self.output_dir))

        if not self.data:
            raise RuntimeError(f"No throughput data found in {self.output_dir}")

        # Establish a canonical ordering of resources
        # This ensures consistent feature vector layout
        self.resource_order = sorted(self.data.keys())
        print(f"Found {len(self.resource_order)} resources: {self.resource_order}")

    def _build_lookup(self):
        """Build the lookup table with 101-dim feature vectors."""
        print("\nBuilding lookup table...")

        for res_name in self.resource_order:
            params, thr = self.data[res_name]
            num_combos, num_windows = thr.shape

            print(
                f"  {res_name}: {num_combos} parameter combinations, {num_windows} windows"
            )

            # Create lookup dict for this resource
            res_lookup = {}

            for combo_idx in range(num_combos):
                # Get parameter values for this combination
                param_vals = params[combo_idx].astype(int)
                param_tuple = tuple(param_vals.tolist())

                # Get throughput samples for this combination across all windows
                samples = thr[combo_idx]

                # Compute 101-dimensional feature vector
                feature_vec = self._compute_feature_vector(samples)

                res_lookup[param_tuple] = feature_vec

            self.lookup[res_name] = res_lookup

        print(f"\nLookup table built successfully!")

    def _get_column_names(self) -> List[str]:
        """
        Generate column names for the feature DataFrame.

        Returns:
            List of column names with actual percentile values:
            resource_raw_p1, resource_raw_p3, resource_raw_p5, ..., resource_raw_p99,
            resource_weighted_p1, resource_weighted_p3, ..., resource_mean
        """
        if self._column_names is not None:
            return self._column_names

        # Get the actual percentile values (1, 3, 5, ..., 99)
        percentiles = np.linspace(1, 99, 50)

        column_names = []
        for res_name in self.resource_order:
            # 50 raw CDF percentiles
            for p in percentiles:
                column_names.append(f"{res_name}_raw_p{int(p)}")
            # 50 weighted CDF percentiles
            for p in percentiles:
                column_names.append(f"{res_name}_weighted_p{int(p)}")
            # Mean value
            column_names.append(f"{res_name}_mean")

        self._column_names = column_names
        return column_names

    def _compute_feature_vector(self, samples: np.ndarray) -> np.ndarray:
        """
        Compute 101-dimensional feature vector from throughput samples.

        Returns:
            Array of shape (101,) containing:
            - samples[0:50]: raw CDF percentiles
            - samples[50:100]: weighted CDF percentiles
            - samples[100]: mean value
        """
        cdf_raw, cdf_weighted, mean_val = utils.compute_cdf_features(
            samples, num_points=50
        )

        # Concatenate into 101-dim vector
        feature_vec = np.concatenate([cdf_raw, cdf_weighted, [mean_val]])

        return feature_vec

    def query(self, resource: str, params: Tuple[int, ...]) -> Optional[np.ndarray]:
        """
        Query the lookup table for a specific resource and parameter combination.

        Args:
            resource: Resource name (e.g., 'rob', 'load_queue')
            params: Tuple of parameter values (e.g., (128,) or (2, 2))

        Returns:
            101-dimensional feature vector, or None if not found
        """
        if resource not in self.lookup:
            return None

        param_tuple = tuple(params) if not isinstance(params, tuple) else params
        return self.lookup[resource].get(param_tuple)

    def get_config_features(
        self, config: models.Config, as_dataframe: bool = False
    ) -> np.ndarray | pd.DataFrame:
        """
        Get the full feature vector for a microarchitecture config.

        Args:
            config: Microarchitecture configuration
            as_dataframe: If True, return pandas DataFrame instead of numpy array

        Returns:
            If as_dataframe=False: Array of shape (N*101,) where N is number of resources
            If as_dataframe=True: DataFrame with 1 row and N*101 columns with descriptive names
        """
        # Map config attributes to resource parameters
        config_map = {
            "rob": (config.rob_size,),
            "load_queue": (config.load_queue_size,),
            "store_queue": (config.store_queue_size,),
            "alu_issue": (config.alu_issue_width,),
            "alu_mul_issue": (config.alu_mul_issue_width,),
            "alu_div_issue": (config.alu_div_issue_width,),
            "fp_issue": (config.fp_issue_width,),
            "ls_issue": (config.ls_issue_width,),
            "load_ls_pipes_lower": (config.num_ls_pipes, config.num_load_pipes),
            "load_ls_pipes_upper": (config.num_ls_pipes, config.num_load_pipes),
            "icache_fills": (config.max_icache_fills,),
            "fetch_buffers": (config.num_fetch_buffers,),
        }

        feature_vectors = []

        for res_name in self.resource_order:
            if res_name not in config_map:
                raise ValueError(f"Unknown resource in data: {res_name}")

            params = config_map[res_name]
            feature_vec = self.query(res_name, params)

            if feature_vec is None:
                # Parameter combination not found - use nearest neighbor
                feature_vec = self._find_nearest_neighbor(res_name, params)

            feature_vectors.append(feature_vec)

        # Concatenate all resource features into single vector
        features = np.concatenate(feature_vectors)

        if as_dataframe:
            return pd.DataFrame([features], columns=self._get_column_names())
        return features

    def _find_nearest_neighbor(
        self, resource: str, target_params: Tuple[int, ...]
    ) -> np.ndarray:
        """
        Find the nearest parameter combination in the lookup table.

        Uses Euclidean distance in parameter space.
        """
        res_lookup = self.lookup[resource]
        target = np.array(target_params, dtype=float)

        min_dist = float("inf")
        nearest_vec = None

        for param_tuple, feature_vec in res_lookup.items():
            params = np.array(param_tuple, dtype=float)
            dist = np.linalg.norm(params - target)

            if dist < min_dist:
                min_dist = dist
                nearest_vec = feature_vec

        if nearest_vec is None:
            raise RuntimeError(
                f"No parameter combinations found for resource {resource}"
            )

        print(
            f"  WARNING: {resource} params {target_params} not found, "
            f"using nearest neighbor (dist={min_dist:.2f})"
        )

        return nearest_vec

    def save(self, filename: str):
        """Save the lookup table to a pickle file."""
        path = Path(filename).resolve()
        with open(path, "wb") as f:
            pickle.dump(
                {
                    "lookup": self.lookup,
                    "resource_order": self.resource_order,
                    "output_dir": str(self.output_dir),
                },
                f,
            )
        print(f"\n✓ Lookup table saved to: {path}")

    @classmethod
    def load(cls, filename: str) -> "ThroughputLookupTable":
        """Load a previously saved lookup table."""
        path = Path(filename).resolve()
        with open(path, "rb") as f:
            data = pickle.load(f)

        # Create instance without loading data
        instance = cls.__new__(cls)
        instance.lookup = data["lookup"]
        instance.resource_order = data["resource_order"]
        instance.output_dir = Path(data["output_dir"])
        instance.data = {}  # Don't need raw data when loading
        instance._column_names = None

        print(f"✓ Lookup table loaded from: {path}")
        print(f"  Resources: {len(instance.resource_order)}")
        print(f"  Feature dimension: {len(instance.resource_order) * 101}")
        return instance

    def get_stats(self) -> Dict[str, int]:
        """Get statistics about the lookup table."""
        stats = {}
        for res_name in self.resource_order:
            stats[res_name] = len(self.lookup[res_name])
        return stats


def main():
    parser = argparse.ArgumentParser(
        description="Build throughput feature lookup table from C++ simulator output",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""Examples:
  # Build lookup table
  python build_throughput_lookup.py -i ../output -o throughput_lookup.pkl

  # Build and test
  python build_throughput_lookup.py -i ../output -o throughput_lookup.pkl --test
        """,
    )

    parser.add_argument(
        "-i",
        "--input-dir",
        type=str,
        default="output",
        help="Directory containing throughput .npy files (default: output)",
    )
    parser.add_argument(
        "-o",
        "--output",
        type=str,
        required=True,
        help="Output pickle file for lookup table (e.g., throughput_lookup.pkl)",
    )
    parser.add_argument(
        "--test",
        action="store_true",
        help="Run test queries after building lookup table",
    )

    args = parser.parse_args()

    # Build lookup table
    print("=" * 70)
    print("BUILDING THROUGHPUT LOOKUP TABLE")
    print("=" * 70)
    print()

    lookup_table = ThroughputLookupTable(output_dir=args.input_dir)

    # Print statistics
    print("\n" + "=" * 70)
    print("STATISTICS")
    print("=" * 70)
    stats = lookup_table.get_stats()
    total_combos = sum(stats.values())

    for res_name in lookup_table.resource_order:
        count = stats[res_name]
        print(f"  {res_name:30s}: {count:6,d} parameter combinations")

    print(f"\n  Total parameter combinations:  {total_combos:6,d}")
    print(f"  Resources:                     {len(lookup_table.resource_order)}")
    print(f"  Feature dimension per config:  {len(lookup_table.resource_order) * 101}")

    # Save lookup table
    lookup_table.save(args.output)

    # Run test queries
    if args.test:
        print("\n" + "=" * 70)
        print("TEST QUERIES")
        print("=" * 70)

        # Test with default config
        default_config = models.Config()
        feature_vec = lookup_table.get_config_features(default_config)
        print(f"\nDefault config feature vector:")
        print(f"  Shape: {feature_vec.shape}")
        print(
            f"  Stats: min={feature_vec.min():.4f}, "
            f"max={feature_vec.max():.4f}, mean={feature_vec.mean():.4f}"
        )

        # Test DataFrame output
        feature_df = lookup_table.get_config_features(default_config, as_dataframe=True)
        print(f"\nDataFrame output:")
        print(f"  Shape: {feature_df.shape[0]} rows x {feature_df.shape[1]} columns")
        print(f"  Sample columns: {list(feature_df.columns[:3])}")

        # Test individual resource query
        print(f"\nQuerying individual resource (ROB, size=128):")
        rob_features = lookup_table.query("rob", (128,))
        if rob_features is not None:
            print(f"  ✓ Found! Shape: {rob_features.shape}")
        else:
            print(f"  ✗ Not found")

        print("\n" + "=" * 70)


if __name__ == "__main__":
    main()
