"""
Build a lookup table for resource throughput features.

This script builds a lookup table mapping microarchitecture configurations to
throughput feature vectors. The lookup table is built once from the throughput
.npy files generated by the C++ simulator, then saved for reuse.

For latency-independent resources the lookup table maps:
  (resource, param_combo) -> 101-dim feature vector

For latency-dependent resources (ROB, LQ, SQ, ICache fills, Fetch Buffers)
throughput varies with the cache configuration, so the key also includes the
cache config index:
  (resource, (cache_config_idx, *param_combo)) -> 101-dim feature vector

The cache config index corresponds to the row ordering in the
<stem>_latencies.npy / <stem>_configs.json produced by annotate_trace.py.

Usage:
  # Build lookup table from throughput data
  python build_throughput_lookup.py -i ../output/<stem> -o throughput_lookup.pkl

  # With per-config support (latency-dependent resources)
  python build_throughput_lookup.py -i ../output/<stem> -o throughput_lookup.pkl \\
      --configs-json ../traces/<stem>_configs.json

  # Test the lookup table
  python build_throughput_lookup.py -i ../output/<stem> -o throughput_lookup.pkl --test
"""

import argparse
import json
import pickle
from glob import glob
from pathlib import Path
from typing import Dict, Optional, Tuple

import numpy as np
import pandas as pd

# Local imports
import registry
import utils
import models


class ThroughputLookupTable:
    """
    Lookup table for resource throughput features.

    Latency-independent resources:
      lookup[resource][(param_tuple,)] = 101-dim feature vector

    Latency-dependent resources:
      lookup[resource][(cache_config_idx, *param_tuple)] = 101-dim feature vector
    """

    def __init__(self, output_dir: str = "output",
                 configs_json: Optional[str] = None):
        """
        Initialize and build the lookup table.

        Args:
            output_dir:   Directory containing throughput .npy files
                          (latency-independent) and config_NNNN/ subdirs
                          (latency-dependent).
            configs_json: Path to <stem>_configs.json produced by
                          annotate_trace.py.  Required when latency-dependent
                          resources are present; maps cache param tuples to
                          config indices.
        """
        self.output_dir = Path(output_dir).resolve()
        self.data = {}     # raw: {res_name: (params, thr)}  — indep only
        self.lookup = {}   # {res_name: {key_tuple: feature_vec}}
        self.resource_order = []
        self._column_names = None

        # Cache config mapping: (l1i_kb, l1d_kb, l2_kb) -> idx
        self._cache_config_to_idx: Dict[Tuple[int, ...], int] = {}
        if configs_json is not None:
            self._load_configs_json(configs_json)

        self._load_and_build()

    # ── Config index mapping ──────────────────────────────────────────────────

    def _load_configs_json(self, path: str) -> None:
        with open(path) as f:
            meta = json.load(f)
        for idx, cfg in enumerate(meta["configs"]):
            self._cache_config_to_idx[tuple(cfg)] = idx
        print(f"Loaded {len(self._cache_config_to_idx)} cache configs from {path}")

    def _cache_config_idx(self, config) -> int:
        """Map a Config's cache parameters to the cache config index."""
        key = (config.l1i_cache_kb, config.l1d_cache_kb, config.l2_cache_kb)
        idx = self._cache_config_to_idx.get(key)
        if idx is None:
            raise ValueError(
                f"Cache config {key} not found in configs.json. "
                f"Available: {sorted(self._cache_config_to_idx.keys())[:5]} ..."
            )
        return idx

    # ── Loading ───────────────────────────────────────────────────────────────

    def _load_and_build(self) -> None:
        latency_dep = registry.LATENCY_DEPENDENT_RESOURCES

        # Canonical resource order: all enabled resources from registry
        self.resource_order = [r.name for r in registry.ENABLED_RESOURCES]
        print(f"Resources: {self.resource_order}")

        for res_name in self.resource_order:
            if res_name in latency_dep:
                self._build_latency_dep(res_name)
            else:
                self._build_latency_indep(res_name)

        print("\nLookup table built successfully!")

    def _build_latency_indep(self, res_name: str) -> None:
        """Load thr_<res>.npy from output_dir and build flat key lookup."""
        path = self.output_dir / f"thr_{res_name}.npy"
        if not path.exists():
            print(f"  [warn] {path} not found — skipping {res_name}")
            self.lookup[res_name] = {}
            return

        params, thr = utils.load_resource_file(str(path), res_name)
        num_combos = thr.shape[0]
        print(f"  {res_name} (indep): {num_combos} param combos")

        res_lookup = {}
        for i in range(num_combos):
            key = tuple(params[i].astype(int).tolist())
            res_lookup[key] = self._compute_feature_vector(thr[i])
        self.lookup[res_name] = res_lookup

    def _build_latency_dep(self, res_name: str) -> None:
        """
        Load thr_<res>.npy from each config_NNNN/ subdirectory.
        Key: (cache_config_idx, *structural_params)
        """
        cfg_dirs = sorted(glob(str(self.output_dir / "config_*")))
        if not cfg_dirs:
            print(f"  [warn] no config_* dirs found — skipping {res_name}")
            self.lookup[res_name] = {}
            return

        res_lookup = {}
        for cfg_dir in cfg_dirs:
            cfg_path = Path(cfg_dir)
            # Extract config index from directory name "config_NNNN"
            cfg_idx = int(cfg_path.name.split("_", 1)[1])

            npy_path = cfg_path / f"thr_{res_name}.npy"
            if not npy_path.exists():
                continue

            params, thr = utils.load_resource_file(str(npy_path), res_name)
            for i in range(thr.shape[0]):
                structural = tuple(params[i].astype(int).tolist())
                key = (cfg_idx,) + structural
                res_lookup[key] = self._compute_feature_vector(thr[i])

        n_cfgs = len(cfg_dirs)
        n_combos = len(res_lookup) // n_cfgs if n_cfgs else 0
        print(f"  {res_name} (dep):   {n_cfgs} configs × {n_combos} param combos")
        self.lookup[res_name] = res_lookup

    # ── Feature computation ───────────────────────────────────────────────────

    def _compute_feature_vector(self, samples: np.ndarray) -> np.ndarray:
        cdf_raw, cdf_weighted, mean_val = utils.compute_cdf_features(
            samples, num_points=50
        )
        return np.concatenate([cdf_raw, cdf_weighted, [mean_val]])

    # ── Query interface ───────────────────────────────────────────────────────

    def query(self, resource: str, key: tuple) -> Optional[np.ndarray]:
        """
        Query the lookup table.

        For latency-independent resources:
            key = (param0,) or (param0, param1)
        For latency-dependent resources:
            key = (cache_config_idx, param0) or (cache_config_idx, param0, param1)
        """
        if resource not in self.lookup:
            return None
        return self.lookup[resource].get(key)

    def get_config_features(
        self, config, as_dataframe: bool = False
    ) -> np.ndarray | pd.DataFrame:
        """
        Get the full feature vector for a microarchitecture config.

        For latency-dependent resources, config must include cache parameters
        (l1i_cache_kb, l1d_cache_kb, l2_cache_kb) that map to a cache config
        index via the loaded configs.json.
        """
        latency_dep = registry.LATENCY_DEPENDENT_RESOURCES
        feature_vectors = []

        for res_name in self.resource_order:
            res_def = registry.RESOURCES_BY_NAME.get(res_name)
            if res_def is None:
                raise ValueError(f"Resource '{res_name}' not in registry.yaml")

            structural = tuple(getattr(config, field) for field in res_def.params)

            if res_name in latency_dep:
                if not self._cache_config_to_idx:
                    raise ValueError(
                        f"Resource '{res_name}' is latency-dependent but no "
                        "configs.json was loaded. Pass --configs-json."
                    )
                cfg_idx = self._cache_config_idx(config)
                key = (cfg_idx,) + structural
            else:
                key = structural

            feature_vec = self.query(res_name, key)
            if feature_vec is None:
                raise ValueError(
                    f"Key {key} not found in lookup table for '{res_name}'. "
                    f"Sample keys: {sorted(self.lookup[res_name].keys())[:3]}"
                )
            feature_vectors.append(feature_vec)

        features = np.concatenate(feature_vectors)

        if as_dataframe:
            return pd.DataFrame([features], columns=self._get_column_names())
        return features

    # ── Column names ──────────────────────────────────────────────────────────

    def _get_column_names(self):
        if self._column_names is not None:
            return self._column_names

        percentiles = utils.PERCENTILE_POINTS
        column_names = []
        for res_name in self.resource_order:
            for p in percentiles:
                column_names.append(f"{res_name}_raw_p{int(p)}")
            for p in percentiles:
                column_names.append(f"{res_name}_weighted_p{int(p)}")
            column_names.append(f"{res_name}_mean")

        self._column_names = column_names
        return column_names

    # ── Persistence ───────────────────────────────────────────────────────────

    def save(self, filename: str) -> None:
        path = Path(filename).resolve()
        with open(path, "wb") as f:
            pickle.dump(
                {
                    "lookup": self.lookup,
                    "resource_order": self.resource_order,
                    "output_dir": str(self.output_dir),
                    "cache_config_to_idx": self._cache_config_to_idx,
                },
                f,
            )
        print(f"\n✓ Lookup table saved to: {path}")

    @classmethod
    def load(cls, filename: str) -> "ThroughputLookupTable":
        path = Path(filename).resolve()
        with open(path, "rb") as f:
            data = pickle.load(f)

        instance = cls.__new__(cls)
        instance.lookup = data["lookup"]
        instance.resource_order = data["resource_order"]
        instance.output_dir = Path(data["output_dir"])
        instance.data = {}
        instance._column_names = None
        instance._cache_config_to_idx = data.get("cache_config_to_idx", {})

        print(f"✓ Lookup table loaded from: {path}")
        print(f"  Resources: {len(instance.resource_order)}")
        print(f"  Feature dimension: "
              f"{len(instance.resource_order) * utils.FEATURES_PER_RESOURCE}")
        return instance

    def get_stats(self) -> Dict[str, int]:
        return {res: len(self.lookup[res]) for res in self.resource_order}


def main():
    parser = argparse.ArgumentParser(
        description="Build throughput feature lookup table from C++ simulator output",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""Examples:
  # Latency-independent only (single-run mode output)
  python build_throughput_lookup.py -i ../output/<stem> -o lookup.pkl

  # With per-cache-config latency-dependent resources
  python build_throughput_lookup.py -i ../output/<stem> -o lookup.pkl \\
      --configs-json ../traces/<stem>_configs.json

  # Build and test
  python build_throughput_lookup.py -i ../output/<stem> -o lookup.pkl --test
        """,
    )

    parser.add_argument("-i", "--input-dir", type=str, default="output",
                        help="Directory with throughput .npy files (default: output)")
    parser.add_argument("-o", "--output", type=str, required=True,
                        help="Output pickle file (e.g., throughput_lookup.pkl)")
    parser.add_argument("--configs-json", type=str, default=None,
                        help="Path to <stem>_configs.json from annotate_trace.py; "
                             "required for latency-dependent resource lookup")
    parser.add_argument("--test", action="store_true",
                        help="Run test queries after building")

    args = parser.parse_args()

    print("=" * 70)
    print("BUILDING THROUGHPUT LOOKUP TABLE")
    print("=" * 70)
    print()

    lookup_table = ThroughputLookupTable(
        output_dir=args.input_dir,
        configs_json=args.configs_json,
    )

    print("\n" + "=" * 70)
    print("STATISTICS")
    print("=" * 70)
    stats = lookup_table.get_stats()
    latency_dep = registry.LATENCY_DEPENDENT_RESOURCES

    for res_name in lookup_table.resource_order:
        dep_tag = "(dep)" if res_name in latency_dep else "(indep)"
        print(f"  {res_name:30s} {dep_tag:7s}: {stats[res_name]:8,d} keys")

    total = sum(stats.values())
    print(f"\n  Total keys:                    {total:8,d}")
    print(f"  Feature dimension per config:  "
          f"{len(lookup_table.resource_order) * utils.FEATURES_PER_RESOURCE}")

    lookup_table.save(args.output)

    if args.test:
        print("\n" + "=" * 70)
        print("TEST QUERIES")
        print("=" * 70)

        default_config = models.Config()

        # Test latency-independent query
        rob_features = lookup_table.query("alu_issue", (4,))
        if rob_features is not None:
            print(f"\n✓ alu_issue (indep, param=4): shape {rob_features.shape}")
        else:
            print("\n✗ alu_issue (indep, param=4): not found")

        # Test latency-dependent query (config 0, ROB=128)
        rob_features = lookup_table.query("rob", (0, 128))
        if rob_features is not None:
            print(f"✓ rob (dep, cfg=0, param=128): shape {rob_features.shape}")
        else:
            print("✗ rob (dep, cfg=0, param=128): not found "
                  "(expected if no per-config data)")

        print("\n" + "=" * 70)


if __name__ == "__main__":
    main()
