"""
gen_registry.py — Generate C++ headers from registry.yaml.

Reads registry.yaml and writes three files into include/:
  include/resources_gen.h      — Resource enum
  include/params_gen.h         — ParamType enum, PARAM_RANGES, get_param_range, ParamSweep
  include/resource_registry.h  — RESOURCE_REGISTRY (enabled flags, func bindings, sweeps)

Run from anamol/:
  python3 python/gen_registry.py [--config registry.yaml] [--out-dir include]

The Makefile runs this automatically when registry.yaml changes.
"""

import argparse
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    print("ERROR: PyYAML is required. Install with: pip install pyyaml", file=sys.stderr)
    sys.exit(1)


def snake_to_upper(name: str) -> str:
    return name.upper()


def write_atomically(path: Path, content: str) -> None:
    """Write to a temp file then rename to avoid partial writes on failure."""
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(content, encoding="utf-8")
    tmp.rename(path)
    print(f"  Wrote {path}")


def gen_resources_h(resources: list, out_dir: Path) -> None:
    lines = []
    lines.append("// AUTO-GENERATED by python/gen_registry.py from registry.yaml")
    lines.append("// DO NOT EDIT MANUALLY — edit registry.yaml and run `make` instead.")
    lines.append("")
    lines.append("#ifndef RESOURCES_GEN_H")
    lines.append("#define RESOURCES_GEN_H")
    lines.append("")
    lines.append("#include <cstdint>")
    lines.append("")
    lines.append("namespace analytical {")
    lines.append("")
    lines.append("enum class Resource : uint8_t {")
    for res in resources:
        lines.append(f"  {snake_to_upper(res['name'])},")
    lines.append("  COUNT  // must be last")
    lines.append("};")
    lines.append("")
    lines.append("}  // namespace analytical")
    lines.append("")
    lines.append("#endif  // RESOURCES_GEN_H")
    lines.append("")

    write_atomically(out_dir / "resources_gen.h", "\n".join(lines))


def gen_params_h(params: list, out_dir: Path) -> None:
    lines = []
    lines.append("// AUTO-GENERATED by python/gen_registry.py from registry.yaml")
    lines.append("// DO NOT EDIT MANUALLY — edit registry.yaml and run `make` instead.")
    lines.append("")
    lines.append("#ifndef PARAMS_GEN_H")
    lines.append("#define PARAMS_GEN_H")
    lines.append("")
    lines.append("#include <array>")
    lines.append("#include <cstddef>")
    lines.append("#include <cstdint>")
    lines.append("#include <span>")
    lines.append("#include <vector>")
    lines.append("")
    lines.append('#include "param_types.h"  // StepType, ParamRange')
    lines.append("")
    lines.append("namespace analytical {")
    lines.append("")
    lines.append("#define PARAM_STEP StepType::BASE_2")
    lines.append("")

    # ParamType enum
    lines.append("////////////////////////////////////////////////////////////////////////////")
    lines.append("// Parameters")
    lines.append("////////////////////////////////////////////////////////////////////////////")
    lines.append("enum class ParamType : uint8_t {")
    for p in params:
        lines.append(f"  {snake_to_upper(p['name'])},")
    lines.append("  COUNT")
    lines.append("};")
    lines.append("")

    # Static arrays for discrete params (non-owning; params_gen.h has static storage)
    discrete_params = [p for p in params if isinstance(p["step"], list)]
    if discrete_params:
        lines.append("namespace detail {")
        for p in discrete_params:
            upper_name = snake_to_upper(p["name"])
            vals_str = ", ".join(str(v) for v in p["step"])
            lines.append(f"inline constexpr uint16_t {upper_name}_VALS[] = {{{vals_str}}};")
        lines.append("}  // namespace detail")
        lines.append("")

    # PARAM_RANGES array
    lines.append("inline constexpr std::array<ParamRange, (size_t)ParamType::COUNT> PARAM_RANGES = {{")
    step_map = {"base2": "PARAM_STEP", "linear": "StepType::LINEAR"}
    for p in params:
        comment = snake_to_upper(p["name"])
        if isinstance(p["step"], list):
            upper_name = snake_to_upper(p["name"])
            lines.append(
                f"    ParamRange{{std::span<const uint16_t>{{detail::{upper_name}_VALS}}}},  // {comment}"
            )
        else:
            step = step_map.get(p["step"])
            if step is None:
                raise ValueError(
                    f"Unknown step type '{p['step']}' for param '{p['name']}'. "
                    "Expected 'base2', 'linear', or a list."
                )
            lines.append(f"    {{{p['min']}, {p['max']}, {step}}},  // {comment}")
    lines.append("}};")
    lines.append("")

    # get_param_range
    lines.append("inline constexpr ParamRange get_param_range(ParamType type) {")
    lines.append("  return PARAM_RANGES[static_cast<size_t>(type)];")
    lines.append("}")
    lines.append("")

    # ParamSweep — boilerplate that depends on ParamType and get_param_range
    lines.append("////////////////////////////////////////////////////////////////////////////")
    lines.append("// ParamSweep — cartesian-product iterator over one or more ParamRanges")
    lines.append("////////////////////////////////////////////////////////////////////////////")
    lines.append("struct ParamSweep {")
    lines.append("  std::vector<ParamType> param_types;")
    lines.append("")
    lines.append("  ParamSweep(std::initializer_list<ParamType> types) : param_types(types) {}")
    lines.append("")
    lines.append("  struct Iterator {")
    lines.append("    using iterator_category = std::forward_iterator_tag;")
    lines.append("    using value_type = std::vector<uint16_t>;")
    lines.append("    using difference_type = std::ptrdiff_t;")
    lines.append("    using pointer = const std::vector<uint16_t>*;")
    lines.append("    using reference = const std::vector<uint16_t>&;")
    lines.append("")
    lines.append("    const std::vector<ParamType>* param_types;")
    lines.append("    std::vector<ParamRange::Iterator> range_iters;")
    lines.append("    std::vector<ParamRange::Iterator> range_ends;")
    lines.append("    bool is_end;")
    lines.append("    mutable std::vector<uint16_t> current;")
    lines.append("")
    lines.append("    Iterator(const std::vector<ParamType>* types, bool end)")
    lines.append("        : param_types(types), is_end(end) {")
    lines.append("      if (!is_end && !param_types->empty()) {")
    lines.append("        for (ParamType pt : *param_types) {")
    lines.append("          auto range = get_param_range(pt);")
    lines.append("          range_iters.push_back(range.begin());")
    lines.append("          range_ends.push_back(range.end());")
    lines.append("        }")
    lines.append("        update_current();")
    lines.append("      }")
    lines.append("    }")
    lines.append("")
    lines.append("    void update_current() {")
    lines.append("      current.clear();")
    lines.append("      for (const auto& iter : range_iters) {")
    lines.append("        current.push_back(*iter);")
    lines.append("      }")
    lines.append("    }")
    lines.append("")
    lines.append("    const std::vector<uint16_t>& operator*() const { return current; }")
    lines.append("")
    lines.append("    Iterator& operator++() {")
    lines.append("      if (is_end || param_types->empty()) return *this;")
    lines.append("")
    lines.append("      for (int i = range_iters.size() - 1; i >= 0; --i) {")
    lines.append("        ++range_iters[i];")
    lines.append("        if (range_iters[i] != range_ends[i]) {")
    lines.append("          update_current();")
    lines.append("          return *this;")
    lines.append("        }")
    lines.append("        auto range = get_param_range((*param_types)[i]);")
    lines.append("        range_iters[i] = range.begin();")
    lines.append("      }")
    lines.append("")
    lines.append("      is_end = true;")
    lines.append("      return *this;")
    lines.append("    }")
    lines.append("")
    lines.append("    bool operator==(const Iterator& other) const {")
    lines.append("      if (is_end && other.is_end) return true;")
    lines.append("      if (is_end != other.is_end) return false;")
    lines.append("      return range_iters == other.range_iters;")
    lines.append("    }")
    lines.append("")
    lines.append("    bool operator!=(const Iterator& other) const { return !(*this == other); }")
    lines.append("  };")
    lines.append("")
    lines.append("  Iterator begin() const { return Iterator(&param_types, false); }")
    lines.append("  Iterator end() const { return Iterator(&param_types, true); }")
    lines.append("};")
    lines.append("")
    lines.append("}  // namespace analytical")
    lines.append("")
    lines.append("#endif  // PARAMS_GEN_H")
    lines.append("")

    write_atomically(out_dir / "params_gen.h", "\n".join(lines))


def gen_resource_registry_h(resources: list, params_by_name: dict, out_dir: Path) -> None:
    lines = []
    lines.append("// AUTO-GENERATED by python/gen_registry.py from registry.yaml")
    lines.append("// DO NOT EDIT MANUALLY — edit registry.yaml and run `make` instead.")
    lines.append("")
    lines.append("#ifndef RESOURCE_REGISTRY_H")
    lines.append("#define RESOURCE_REGISTRY_H")
    lines.append("")
    lines.append("// models.h transitively includes resources_gen.h and params_gen.h")
    lines.append('#include "models.h"')
    lines.append("")
    lines.append("namespace analytical {")
    lines.append("")
    lines.append("// RESOURCE_REGISTRY — one entry per resource in registry.yaml order.")
    lines.append("// To disable a resource: set enabled: false in registry.yaml and re-run make.")
    lines.append("// C++ function convention: get_thr_<resource_name>(window, p[0], ...)")
    lines.append("static const std::vector<ResourceEntry> RESOURCE_REGISTRY = {")

    for res in resources:
        name = res["name"]
        enum_name = snake_to_upper(name)
        enabled = "true" if res["enabled"] else "false"
        res_params = res["params"]

        # Build the lambda body based on number of params
        if len(res_params) == 1:
            func_call = f"get_thr_{name}(w, p[0])"
        elif len(res_params) == 2:
            func_call = f"get_thr_{name}(w, p[0], p[1])"
        else:
            raise ValueError(f"Resource '{name}' has {len(res_params)} params; only 1 or 2 supported")

        # Build the ParamSweep initializer
        param_enum_list = ", ".join(
            f"ParamType::{snake_to_upper(p)}" for p in res_params
        )

        lines.append("    {")
        lines.append(f"        Resource::{enum_name},")
        lines.append(f'        "{name}",')
        lines.append(f"        {enabled},")
        lines.append(f"        [](const auto& w, const auto& p) {{ return {func_call}; }},")
        lines.append(f"        ParamSweep{{{param_enum_list}}},")
        lines.append("    },")

    lines.append("};")
    lines.append("")
    lines.append("}  // namespace analytical")
    lines.append("")
    lines.append("#endif  // RESOURCE_REGISTRY_H")
    lines.append("")

    write_atomically(out_dir / "resource_registry.h", "\n".join(lines))


def main():
    parser = argparse.ArgumentParser(
        description="Generate C++ headers from registry.yaml"
    )
    parser.add_argument(
        "--config",
        type=str,
        default="registry.yaml",
        help="Path to registry.yaml (default: registry.yaml)",
    )
    parser.add_argument(
        "--out-dir",
        type=str,
        default="include",
        help="Output directory for generated headers (default: include)",
    )
    args = parser.parse_args()

    config_path = Path(args.config).resolve()
    out_dir = Path(args.out_dir).resolve()

    if not config_path.exists():
        print(f"ERROR: registry file not found: {config_path}", file=sys.stderr)
        sys.exit(1)

    out_dir.mkdir(parents=True, exist_ok=True)

    print(f"Reading: {config_path}")
    with open(config_path) as f:
        registry = yaml.safe_load(f)

    params = registry.get("params", [])
    resources = registry.get("resources", [])

    # Validate: all resource params must exist in the params list
    params_by_name = {p["name"]: p for p in params}
    for res in resources:
        for p in res["params"]:
            if p not in params_by_name:
                print(
                    f"ERROR: Resource '{res['name']}' references unknown param '{p}'",
                    file=sys.stderr,
                )
                sys.exit(1)

    print(f"Generating headers in: {out_dir}")
    gen_resources_h(resources, out_dir)
    gen_params_h(params, out_dir)
    gen_resource_registry_h(resources, params_by_name, out_dir)
    print("Done.")


if __name__ == "__main__":
    main()
