#ifndef PARAM_TYPES_H
#define PARAM_TYPES_H

// param_types.h — manual infrastructure for parameter sweeping.
// Contains only StepType and ParamRange.
//
// ParamSweep, ParamType, PARAM_RANGES, and get_param_range() live in
// params_gen.h (auto-generated from registry.yaml), which includes this file.

#include <cstddef>
#include <cstdint>
#include <iterator>
#include <span>

namespace analytical {

////////////////////////////////////////////////////////////////////////////
// Step type
////////////////////////////////////////////////////////////////////////////
enum class StepType : uint8_t { LINEAR, BASE_2, DISCRETE };

////////////////////////////////////////////////////////////////////////////
// ParamRange — iterable range over one parameter's sweep values
////////////////////////////////////////////////////////////////////////////
struct ParamRange {
  uint16_t min;
  uint16_t max;
  StepType step_type;
  // Non-owning view into a static constexpr array (generated by params_gen.h).
  // Empty unless step_type == DISCRETE. No heap allocation; no ownership.
  std::span<const uint16_t> discrete_vals;

  // Constructor for BASE_2 / LINEAR
  constexpr ParamRange(uint16_t min_val, uint16_t max_val,
                       StepType step = StepType::BASE_2)
      : min(min_val), max(max_val), step_type(step), discrete_vals{} {}

  // Constructor for DISCRETE — vals must be a static constexpr array
  explicit constexpr ParamRange(std::span<const uint16_t> vals)
      : min(vals.front()), max(vals.back()), step_type(StepType::DISCRETE),
        discrete_vals(vals) {}

  struct Iterator {
    using iterator_category = std::forward_iterator_tag;
    using value_type = uint16_t;
    using difference_type = std::ptrdiff_t;
    using pointer = uint16_t*;
    using reference = uint16_t&;

    uint16_t current;
    uint16_t max;
    StepType step_type;
    std::span<const uint16_t> discrete_vals;
    uint16_t discrete_idx;

    // Constructor for BASE_2 / LINEAR
    constexpr Iterator(uint16_t c, uint16_t m, StepType st)
        : current(c), max(m), step_type(st), discrete_vals{}, discrete_idx(0) {}

    // Constructor for DISCRETE
    constexpr Iterator(std::span<const uint16_t> dv, uint16_t di)
        : current(di < dv.size() ? dv[di] : 0), max(0),
          step_type(StepType::DISCRETE), discrete_vals(dv), discrete_idx(di) {}

    uint16_t operator*() const { return current; }

    Iterator& operator++() {
      if (step_type == StepType::DISCRETE) {
        ++discrete_idx;
        if (discrete_idx < discrete_vals.size())
          current = discrete_vals[discrete_idx];
      } else if (step_type == StepType::LINEAR) {
        ++current;
      } else {  // BASE_2
        if (current == 0) {
          current = 1;
        } else {
          current *= 2;
        }
      }
      return *this;
    }

    bool operator==(const Iterator& other) const {
      if (step_type == StepType::DISCRETE)
        return discrete_idx == other.discrete_idx;
      return current == other.current;
    }

    bool operator!=(const Iterator& other) const { return !(*this == other); }
  };

  Iterator begin() const {
    if (step_type == StepType::DISCRETE)
      return Iterator(discrete_vals, 0);
    return Iterator(min, max, step_type);
  }
  Iterator end() const {
    if (step_type == StepType::DISCRETE)
      return Iterator(discrete_vals, static_cast<uint16_t>(discrete_vals.size()));
    uint16_t end_val = min;
    if (step_type == StepType::BASE_2) {
      end_val = (min == 0) ? 1 : min;
      while (end_val <= max) end_val *= 2;
    } else {
      end_val = max + 1;
    }
    return Iterator(end_val, max, step_type);
  }
};

}  // namespace analytical

#endif  // PARAM_TYPES_H
