// AUTO-GENERATED by python/gen_registry.py from registry.yaml
// DO NOT EDIT MANUALLY — edit registry.yaml and run `make` instead.

#ifndef RESOURCE_REGISTRY_H
#define RESOURCE_REGISTRY_H

// models.h transitively includes resources_gen.h and params_gen.h
#include "models.h"

namespace analytical {

// RESOURCE_REGISTRY — one entry per resource in registry.yaml order.
// To disable a resource: set enabled: false in registry.yaml and re-run make.
// C++ function convention: get_thr_<resource_name>(window, p[0], ...)
static const std::vector<ResourceEntry> RESOURCE_REGISTRY = {
    {
        Resource::ROB,
        "rob",
        true,
        [](const auto& w, const auto& p) { return get_thr_rob(w, p[0]); },
        ParamSweep{ParamType::ROB_SIZE},
    },
    {
        Resource::LOAD_QUEUE,
        "load_queue",
        true,
        [](const auto& w, const auto& p) { return get_thr_load_queue(w, p[0]); },
        ParamSweep{ParamType::LOAD_QUEUE_SIZE},
    },
    {
        Resource::STORE_QUEUE,
        "store_queue",
        true,
        [](const auto& w, const auto& p) { return get_thr_store_queue(w, p[0]); },
        ParamSweep{ParamType::STORE_QUEUE_SIZE},
    },
    {
        Resource::ALU_ISSUE,
        "alu_issue",
        true,
        [](const auto& w, const auto& p) { return get_thr_alu_issue(w, p[0]); },
        ParamSweep{ParamType::ALU_ISSUE_WIDTH},
    },
    {
        Resource::ALU_MUL_ISSUE,
        "alu_mul_issue",
        true,
        [](const auto& w, const auto& p) { return get_thr_alu_mul_issue(w, p[0]); },
        ParamSweep{ParamType::ALU_MUL_ISSUE_WIDTH},
    },
    {
        Resource::ALU_DIV_ISSUE,
        "alu_div_issue",
        true,
        [](const auto& w, const auto& p) { return get_thr_alu_div_issue(w, p[0]); },
        ParamSweep{ParamType::ALU_DIV_ISSUE_WIDTH},
    },
    {
        Resource::FP_ISSUE,
        "fp_issue",
        true,
        [](const auto& w, const auto& p) { return get_thr_fp_issue(w, p[0]); },
        ParamSweep{ParamType::FP_ISSUE_WIDTH},
    },
    {
        Resource::LS_ISSUE,
        "ls_issue",
        true,
        [](const auto& w, const auto& p) { return get_thr_ls_issue(w, p[0]); },
        ParamSweep{ParamType::LS_ISSUE_WIDTH},
    },
    {
        Resource::LOAD_LS_PIPES_LOWER,
        "load_ls_pipes_lower",
        true,
        [](const auto& w, const auto& p) { return get_thr_load_ls_pipes_lower(w, p[0], p[1]); },
        ParamSweep{ParamType::NUM_LS_PIPES, ParamType::NUM_LOAD_PIPES},
    },
    {
        Resource::LOAD_LS_PIPES_UPPER,
        "load_ls_pipes_upper",
        true,
        [](const auto& w, const auto& p) { return get_thr_load_ls_pipes_upper(w, p[0], p[1]); },
        ParamSweep{ParamType::NUM_LS_PIPES, ParamType::NUM_LOAD_PIPES},
    },
    {
        Resource::ICACHE_FILLS,
        "icache_fills",
        true,
        [](const auto& w, const auto& p) { return get_thr_icache_fills(w, p[0]); },
        ParamSweep{ParamType::MAX_ICACHE_FILLS},
    },
    {
        Resource::FETCH_BUFFERS,
        "fetch_buffers",
        false,
        [](const auto& w, const auto& p) { return get_thr_fetch_buffers(w, p[0]); },
        ParamSweep{ParamType::NUM_FETCH_BUFFERS},
    },
};

}  // namespace analytical

#endif  // RESOURCE_REGISTRY_H
