// AUTO-GENERATED by python/gen_registry.py from registry.yaml
// DO NOT EDIT MANUALLY — edit registry.yaml and run `make` instead.

#ifndef RESOURCES_GEN_H
#define RESOURCES_GEN_H

#include <cstdint>

namespace analytical {

enum class Resource : uint8_t {
  ROB,
  LOAD_QUEUE,
  STORE_QUEUE,
  ALU_ISSUE,
  ALU_MULT_DIV_ISSUE,
  FP_ISSUE,
  FP_MULT_DIV_ISSUE,
  LS_ISSUE,
  LOAD_LS_PIPES_LOWER,
  LOAD_LS_PIPES_UPPER,
  ICACHE_FILLS,
  FETCH_BUFFERS,
  COUNT  // must be last
};

}  // namespace analytical

#endif  // RESOURCES_GEN_H
